=== AnnaVolynets22/ta_lab_java/src/main/resources/beer.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "http://example.com/example.json",
  "type": "array",
  "title": "The Root Schema",
  "description": "The root schema comprises the entire JSON document.",
  "items": {
    "$id": "#/items",
    "type": "object",
    "title": "The Items Schema",
    "description": "",
    "default": {},
    "examples": [
      {
        "name": "Corona",
        "manufacturer": "Corona manufacturer",
        "ingredients": [
          "Water",
          "Sugar",
          "Malted barley"
        ],
        "type": "BLACK",
        "AI": "true",
        "chars": {
          "foodValue": "123",
          "pouringMethod": {
            "material": "Plastic",
            "volume": "0.5"
          },
          "filter": "false",
          "alcoholVolume": "14",
          "transparency": "12.5"
        },
        "@beerId": "123"
      },
      {
        "@beerId": "456",
        "name": "Baltyka",
        "manufacturer": "Baltyka manufacturer",
        "ingredients": [
          "Water",
          "Sugar",
          "Malted barley"
        ],
        "type": "LIGHT",
        "AI": "true",
        "chars": {
          "foodValue": "123",
          "pouringMethod": {
            "material": "Glass",
            "volume": "0.5"
          },
          "filter": "true",
          "alcoholVolume": "12",
          "transparency": "14.5"
        }
      }
    ],
    "required": [
      "@beerId",
      "name",
      "type",
      "AI",
      "manufacturer",
      "ingredients",
      "chars"
    ],
    "properties": {
      "@beerId": {
        "$id": "#/items/properties/@beerId",
        "type": "string",
        "title": "The @beerid Schema",
        "description": "",
        "default": "",
        "examples": [
          "123"
        ]
      },
      "name": {
        "$id": "#/items/properties/name",
        "type": "string",
        "title": "The Name Schema",
        "description": "",
        "default": "",
        "examples": [
          "Corona"
        ]
      },
      "type": {
        "$id": "#/items/properties/type",
        "type": "string",
        "title": "The Type Schema",
        "description": "",
        "default": "",
        "examples": [
          "BLACK"
        ]
      },
      "AI": {
        "$id": "#/items/properties/AI",
        "type": "string",
        "title": "The Ai Schema",
        "description": "",
        "default": "",
        "examples": [
          "true"
        ]
      },
      "manufacturer": {
        "$id": "#/items/properties/manufacturer",
        "type": "string",
        "title": "The Manufacturer Schema",
        "description": "",
        "default": "",
        "examples": [
          "Corona manufacturer"
        ]
      },
      "ingredients": {
        "$id": "#/items/properties/ingredients",
        "type": "array",
        "title": "The Ingredients Schema",
        "description": "",
        "default": [],
        "items": {
          "$id": "#/items/properties/ingredients/items",
          "type": "string",
          "title": "The Items Schema",
          "description": "",
          "default": "",
          "examples": [
            "Water",
            "Sugar",
            "Malted barley"
          ]
        }
      },
      "chars": {
        "$id": "#/items/properties/chars",
        "type": "object",
        "title": "The Chars Schema",
        "description": "",
        "default": {},
        "examples": [
          {
            "foodValue": "123",
            "pouringMethod": {
              "material": "Plastic",
              "volume": "0.5"
            },
            "filter": "false",
            "alcoholVolume": "14",
            "transparency": "12.5"
          }
        ],
        "required": [
          "alcoholVolume",
          "transparency",
          "filter",
          "foodValue",
          "pouringMethod"
        ],
        "properties": {
          "alcoholVolume": {
            "$id": "#/items/properties/chars/properties/alcoholVolume",
            "type": "string",
            "title": "The Alcoholvolume Schema",
            "description": "",
            "default": "",
            "examples": [
              "14"
            ]
          },
          "transparency": {
            "$id": "#/items/properties/chars/properties/transparency",
            "type": "string",
            "title": "The Transparency Schema",
            "description": "",
            "default": "",
            "examples": [
              "12.5"
            ]
          },
          "filter": {
            "$id": "#/items/properties/chars/properties/filter",
            "type": "string",
            "title": "The Filter Schema",
            "description": "",
            "default": "",
            "examples": [
              "false"
            ]
          },
          "foodValue": {
            "$id": "#/items/properties/chars/properties/foodValue",
            "type": "string",
            "title": "The Foodvalue Schema",
            "description": "",
            "default": "",
            "examples": [
              "123"
            ]
          },
          "pouringMethod": {
            "$id": "#/items/properties/chars/properties/pouringMethod",
            "type": "object",
            "title": "The Pouringmethod Schema",
            "description": "An explanation about the purpose of this instance.",
            "default": {},
            "examples": [
              {
                "volume": "0.5",
                "material": "Plastic"
              }
            ],
            "required": [
              "volume",
              "material"
            ],
            "properties": {
              "volume": {
                "$id": "#/items/properties/chars/properties/pouringMethod/properties/volume",
                "type": "string",
                "title": "The Volume Schema",
                "description": "",
                "default": "",
                "examples": [
                  "0.5"
                ]
              },
              "material": {
                "$id": "#/items/properties/chars/properties/pouringMethod/properties/material",
                "type": "string",
                "title": "The Material Schema",
                "description": "",
                "default": "",
                "examples": [
                  "Plastic"
                ]
              }
            }
          }
        }
      }
    }
  }
}

=== AnnaVolynets22/ta_lab_java/src/main/resources/beer.json
[
  {
    "@beerId": "123",
    "name": "Corona",
    "type": "BLACK",
    "AI": "true",
    "manufacturer": "Corona manufacturer",
    "ingredients": [
      "Water",
      "Sugar",
      "Malted barley"
    ],
    "chars": {
      "alcoholVolume": "14",
      "transparency": "12.5",
      "filter": "false",
      "foodValue": "123",
      "pouringMethod": {
        "volume": "0.5",
        "material": "Plastic"
      }
    }
  },
  {
    "@beerId": "456",
    "name": "Baltyka",
    "type": "LIGHT",
    "AI": "true",
    "manufacturer": "Baltyka manufacturer",
    "ingredients": [
      "Water",
      "Sugar",
      "Malted barley"
    ],
    "chars": {
      "alcoholVolume": "12",
      "transparency": "14.5",
      "filter": "true",
      "foodValue": "123",
      "pouringMethod": {
        "volume": "0.5",
        "material": "Glass"
      }
    }
  }
]
